---
kubeconfig: "{{  openshift.common.config_base }}/node/{{ 'system:node:' +  openshift.common.hostname }}.kubeconfig"

cni_conf_dir: "/etc/cni/net.d/"
cni_bin_dir: "/opt/cni/bin/"

calico_ipv4pool_ipip: "always"

calico_log_dir: "/var/log/calico"
calico_node_image: "quay.io/calico/node:v2.6.7"
calico_cni_image: "quay.io/calico/cni:v1.11.2"
