---
- name: Calico Master | Assure the calico certs have been generated
  stat:
    path: "{{ item }}"
  with_items:
  - "{{ calico_etcd_ca_cert_file }}"
  - "{{ calico_etcd_cert_file }}"
  - "{{ calico_etcd_key_file }}"

- name: Calico Master | Create temp directory
  command: mktemp -d /tmp/openshift-ansible-XXXXXXX
  register: mktemp
  changed_when: False

# - name: Create objects
#   include: oc_apply.yaml
#   vars:
#     kubeconfig: "{{ mktemp.stdout }}/admin.kubeconfig"
#     # namespace: "{{ openshift_metrics_project }}"
#     file_name: "{{ item.source }}"
#     file_content: "{{ item.content | b64decode | from_yaml }}"
#   with_items: "{{ object_defs.results }}"

- name: Calico Master | Write Calico 
  template:
    dest: "{{ mktemp.stdout }}/calico.yml"
    src: calico.yml.j2

- name: Calico Master | Launch Calico
  command: >
    {{ openshift.common.client_binary }} create
    -f {{ mktemp.stdout }}/calico.yml
    --config={{ openshift.common.config_base }}/master/admin.kubeconfig
  register: calico_create_output
  failed_when: "('already exists' not in calico_create_output.stderr) and ('created' not in calico_create_output.stdout) and calico_create_output.rc != 0"
  changed_when: ('created' in calico_create_output.stdout)

- name: Calico Master | Delete temp directory
  file:
    name: "{{ mktemp.stdout }}"
    state: absent
  changed_when: False


- name: Calico Master | oc adm policy add-scc-to-user privileged system:serviceaccount:kube-system:calico-node
  oc_adm_policy_user:
    user: system:serviceaccount:kube-system:calico-node
    resource_kind: scc
    resource_name: privileged
    state: present

- name: Calico Master | oc adm policy add-scc-to-user privileged system:serviceaccount:kube-system:calico-policy-controller
  oc_adm_policy_user:
    user: system:serviceaccount:kube-system:calico-policy-controller
    resource_kind: scc
    resource_name: privileged
    state: present

- name: Calico Master | oc adm policy add-scc-to-user privileged system:serviceaccount:kube-system:calico-kube-controllers
  oc_adm_policy_user:
    user: system:serviceaccount:kube-system:calico-kube-controllers
    resource_kind: scc
    resource_name: privileged
    state: present

- name: Download Calicoctl
  become: yes
  get_url:
    url: "{{ calico_url_calicoctl }}"
    dest: "{{ calicoctl_bin_dir }}"
    mode: a+x
