---
- name: Check for legacy service
  stat:
    path: /lib/systemd/system/calico.service
  register: sym
- fail:
    msg: You are running a systemd based installation of Calico. Please run the calico upgrade playbook to upgrade to a self-hosted install.
  when: sym.stat.exists

- name: Prepull Images
    command: "docker pull {{ calico_node_image }}"

- name: Apply node label
    delegate_to: "{{ groups.oo_first_master.0 }}"
    command: >
      {{ openshift.common.client_binary }} --config={{ openshift.common.config_base }}/master/admin.kubeconfig label node {{ openshift.node.nodename | lower }} --overwrite projectcalico.org/ds-ready=true
