---
- name: Calico Node | Error if invalid cert arguments
  fail:
    msg: "Must provide all or none for the following etcd params: calico_etcd_cert_dir, calico_etcd_ca_cert_file, calico_etcd_cert_file, calico_etcd_key_file, calico_etcd_endpoints"
  when:
  - calico_etcd_cert_dir is defined or calico_etcd_ca_cert_file is defined or calico_etcd_cert_file is defined or calico_etcd_key_file is defined or calico_etcd_endpoints is defined
  - not (calico_etcd_cert_dir is defined and calico_etcd_ca_cert_file is defined and calico_etcd_cert_file is defined and calico_etcd_key_file is defined and calico_etcd_endpoints is defined)

- name: Calico Node | Generate OpenShift-etcd certs
  include_role:
    name: etcd
    tasks_from: client_certificates
  when: calico_etcd_ca_cert_file is not defined or calico_etcd_cert_file is not defined or calico_etcd_key_file is not defined or calico_etcd_endpoints is not defined or calico_etcd_cert_dir is not defined
  vars:
    etcd_cert_prefix: calico.etcd-
    etcd_cert_config_dir: "{{ openshift.common.config_base }}/calico"
    embedded_etcd: "{{ hostvars[groups.oo_first_master.0].openshift.master.embedded_etcd }}"
    etcd_ca_host: "{{ groups.oo_etcd_to_config.0 }}"
    etcd_cert_subdir: "openshift-calico-{{ openshift.common.hostname }}"
  static: true

- name: Calico Node | Set etcd cert location facts
  when: calico_etcd_ca_cert_file is not defined or calico_etcd_cert_file is not defined or calico_etcd_key_file is not defined or calico_etcd_endpoints is not defined or calico_etcd_cert_dir is not defined
  set_fact:
    calico_etcd_ca_cert_file: "/etc/origin/calico/calico.etcd-ca.crt"
    calico_etcd_cert_file: "/etc/origin/calico/calico.etcd-client.crt"
    calico_etcd_key_file: "/etc/origin/calico/calico.etcd-client.key"
    calico_etcd_endpoints: "{{ hostvars[groups.oo_first_master.0].openshift.master.etcd_urls | join(',') }}"
    calico_etcd_cert_dir: "/etc/origin/calico/"

- name: Calico Node | Error if no certs set.
  fail:
    msg: "Invalid etcd configuration for calico."
  when: item is not defined or item == ''
  with_items:
  - calico_etcd_ca_cert_file
  - calico_etcd_cert_file
  - calico_etcd_key_file
  - calico_etcd_endpoints

- name: Calico Node | Assure the calico certs are present
  stat:
    path: "{{ item }}"
  with_items:
  - "{{ calico_etcd_ca_cert_file }}"
  - "{{ calico_etcd_cert_file }}"
  - "{{ calico_etcd_key_file }}"

- name: Calico Node | Assure Calico conf dir exists
  become: yes
  file: path=/etc/calico/ state=directory

- name: Calico Node | Set calicoctl.cfg
  template:
    src: calicoctl.cfg.j2
    dest: "/etc/calico/calicoctl.cfg"

- name: Check selinux label of '{{ cni_bin_dir }}'
  command: >
    stat -c '%C' {{ cni_bin_dir }}
  register: l_cn_bin_dir_selinux_labels

- debug:
    msg: "{{ l_cn_bin_dir_selinux_labels }}"

- name: Make sure the '{{ cni_bin_dir }}' has the proper label
  command: >
    chcon -t svirt_sandbox_file_t  "{{ cni_bin_dir }}"
  when:
  - l_cn_bin_dir_selinux_labels.rc == 0
  - "'svirt_sandbox_file_t' not in l_cn_bin_dir_selinux_labels.stdout"

- name: Check selinux label of '{{ cni_conf_dir }}'
  command: >
    stat -c '%C' {{ cni_conf_dir }}
  register: l_cni_conf_dir_selinux_labels

- debug:
    msg: "{{ l_cni_conf_dir_selinux_labels }}"

- name: Make sure the '{{ cni_conf_dir }}' has the proper label
  command: >
    chcon -t svirt_sandbox_file_t  "{{ cni_conf_dir }}"
  when:
  - l_cni_conf_dir_selinux_labels.rc == 0
  - "'svirt_sandbox_file_t' not in l_cni_conf_dir_selinux_labels.stdout"
