---
- block:
  - name: Record RPM based calico version
    command: rpm -qa --qf '%{version}' calico\*
    args:
      warn: no
    register: calico_rpm_version
    failed_when: false
    # AUDIT:changed_when: `false` because we are only inspecting
    # state, not manipulating anything
    changed_when: false
  - debug:
      msg: "calico rpm version {{ calico_rpm_version.stdout }} detected"
  when:
  - not openshift_is_containerized | bool

- block:
  - name: Record containerized calico version (docker)
    command: docker exec calico_container rpm -qa --qf '%{version}' calico\*
    register: calico_container_version_docker
    failed_when: false
    # AUDIT:changed_when: `false` because we are only inspecting
    # state, not manipulating anything
    changed_when: false
    when:
    - not l_is_calico_system_container | bool

    # Given a register variables is set even if the whwen condition
    # is false, we need to set calico_container_version separately
  - set_fact:
      calico_container_version: "{{ calico_container_version_docker.stdout }}"
    when:
    - not l_is_calico_system_container | bool

  - name: Record containerized calico version (runc)
    command: runc exec calico rpm -qa --qf '%{version}' calico\*
    register: calico_container_version_runc
    failed_when: false
    # AUDIT:changed_when: `false` because we are only inspecting
    # state, not manipulating anything
    changed_when: false
    when:
    - l_is_calico_system_container | bool

    # Given a register variables is set even if the whwen condition
    # is false, we need to set calico_container_version separately
  - set_fact:
      calico_container_version: "{{ calico_container_version_runc.stdout }}"
    when:
    - l_is_calico_system_container | bool

  - debug:
      msg: "calico containerized version {{ calico_container_version }} detected"
  when:
  - openshift_is_containerized | bool
